spring:
  profiles:
    active: dev
  application:
    name: sky-drinks
  datasource:
    url: jdbc:mysql://localhost:3306/skydrinks?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
