spring:
  datasource:
    url: {JDBC_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  config:
    expiration: 604800 # One week

my:
  cors:
    origins: ["https://sky-drinks-ui.herokuapp.com"]
