spring:
  application:
    name: sky-drinks
  datasource:
    url: jdbc:mysql://localhost:3306/skydrinks?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 5MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

my:
  files:
      upload-dir: ./uploaded-files
