spring:
  datasource:
    url: {JDBC_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

jwt:
  config:
    expiration: 604800 # One week

my:
  cors:
    origins: ["https://sky-drinks-ui.vercel.app", "https://sky-drinks-ui.vercel.app", "https://sky-drinks*.vercel.app"]
