spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

jwt:
  config:
    expiration: 604800 # One week
    privateKey: ${JWT_PRIVATE_KEY}

my:
  cors:
    origins: ["https://sky-drinks-ui.vercel.app", "https://sky-drinks.vercel.app", "https://sky-drinks*.vercel.app", "https://skybar.vercel.app"]
