spring:
  profiles:
    active: dev
  application:
    name: sky-drinks
  datasource:
    url: jdbc:mysql://localhost:3306/skydrinks?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

server:
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /api/v1
    multipart:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

my:
  files:
      upload-dir: ./uploaded-files
