spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: {MYSQL_URL}
    username: {MYSQLUSER}
    password: {MYSQLPASSWORD}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

jwt:
  config:
    expiration: 604800 # One week
    privateKey: {JWT_PRIVATE_KEY}

my:
  cors:
    origins: ["https://sky-drinks-ui.vercel.app", "https://sky-drinks.vercel.app", "https://sky-drinks*.vercel.app", "https://skybar.vercel.app"]
